/**
 * Audit 2026-06-10 cli-commands-4 regression test.
 *
 * The launchd plist is generated by substituting __BINARY_PATH__ / __HOME__
 * into <string> elements. Without XML escaping, a path under a directory named
 * e.g. "a&b" emitted malformed XML and launchctl silently rejected the
 * LaunchAgent. `xmlEscape` must encode &, <, >, ", and '.
 */

import { describe, expect, it } from "vitest";
import { xmlEscape } from "../launchd.js";

describe("cli-commands-4 — xmlEscape for plist substitution", () => {
  it("escapes the ampersand (most common path footgun)", () => {
    expect(xmlEscape("/opt/a&b/node")).toBe("/opt/a&amp;b/node");
  });

  it("escapes all five XML character-data special chars", () => {
    expect(xmlEscape(`& < > " '`)).toBe("&amp; &lt; &gt; &quot; &apos;");
  });

  it("escapes the ampersand first so entities are not double-encoded", () => {
    // A literal "&lt;" in the path must become "&amp;lt;", not "&lt;".
    expect(xmlEscape("&lt;")).toBe("&amp;lt;");
  });

  it("leaves a normal path untouched", () => {
    expect(xmlEscape("/Users/me/.npm-global/bin/patchwork-os")).toBe(
      "/Users/me/.npm-global/bin/patchwork-os",
    );
  });

  it("produces a substring that is valid inside an XML <string> element", () => {
    const escaped = xmlEscape("/home/a&b/<bin>/node");
    const xml = `<string>${escaped}</string>`;
    // No raw &, <, or > survive between the element tags.
    const inner = xml.slice("<string>".length, -"</string>".length);
    expect(inner).not.toMatch(/&(?!(amp|lt|gt|quot|apos);)/);
    expect(inner).not.toContain("<bin>");
  });
});
