/**
 * Mock responses for demo mode. Returned by bridgeFetch() when
 * NEXT_PUBLIC_DEMO_MODE=true so the dashboard shows realistic data
 * without a running bridge.
 */

const SESSION_START = Date.now() - 3 * 60 * 60 * 1000; // "started" 3h ago

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function ago(ms: number): number {
  return Date.now() - ms;
}

// ---------------------------------------------------------------------------
// Mock datasets
// ---------------------------------------------------------------------------

const MOCK_APPROVALS = [
  {
    callId: "demo-1",
    toolName: "github.create_pull_request",
    tier: "medium",
    requestedAt: ago(4 * 60 * 1000),
    summary: "Open PR: feat/demo-mode dashboard",
    sessionId: "sess-demo",
  },
  {
    callId: "demo-2",
    toolName: "slack.post_message",
    tier: "low",
    requestedAt: ago(11 * 60 * 1000),
    summary: "Post to #engineering: sprint review prep",
    sessionId: "sess-demo",
  },
  {
    callId: "demo-3",
    toolName: "linear.create_issue",
    tier: "high",
    requestedAt: ago(23 * 60 * 1000),
    summary: "Create issue: Fix bridge status inconsistency",
    sessionId: "sess-demo",
  },
];

const MOCK_RECIPES = [
  {
    name: "morning-brief",
    description: "Daily 6am digest delivered to Slack",
    trigger: "schedule",
    enabled: true,
    lastRun: ago(18 * 60 * 60 * 1000),
    source: "github:patchworkos/recipes/recipes/morning-brief",
  },
  {
    name: "incident-war-room",
    description: "Ops incident response pipeline — chains to incident-notify and post-incident-report",
    trigger: "webhook",
    webhookPath: "/incident-war-room",
    enabled: true,
    lastRun: ago(2 * 24 * 60 * 60 * 1000),
    source: "github:patchworkos/recipes/recipes/incident-war-room",
  },
  {
    name: "incident-notify",
    description: "Triggered by incident-war-room — posts to #incidents Slack and pages on-call",
    trigger: "recipe",
    enabled: true,
    lastRun: ago(2 * 24 * 60 * 60 * 1000),
    source: "github:patchworkos/recipes/recipes/incident-notify",
  },
  {
    name: "post-incident-report",
    description: "Triggered by incident-notify — appends post-incident summary to Notion",
    trigger: "recipe",
    enabled: true,
    lastRun: ago(2 * 24 * 60 * 60 * 1000),
    source: "github:patchworkos/recipes/recipes/post-incident-report",
  },
  {
    name: "sprint-review-prep",
    description: "Pull Linear issues, post to #engineering",
    trigger: "manual",
    enabled: false,
    lastRun: ago(5 * 24 * 60 * 60 * 1000),
    source: "github:patchworkos/recipes/recipes/sprint-review-prep",
  },
];

const MOCK_TASKS = {
  tasks: [
    {
      taskId: "task-1",
      prompt: "Review open PRs and summarise for standup",
      status: "done",
      driver: "claude",
      startedAt: ago(45 * 60 * 1000),
      finishedAt: ago(41 * 60 * 1000),
      output: "Found 3 open PRs. Summary posted to #engineering.",
    },
    {
      taskId: "task-2",
      prompt: "Run sprint-review-prep recipe",
      status: "done",
      driver: "claude",
      startedAt: ago(2 * 60 * 60 * 1000),
      finishedAt: ago(118 * 60 * 1000),
      output: "Sprint review digest sent to Slack.",
    },
    {
      taskId: "task-3",
      prompt: "Check Linear backlog for P0 issues",
      status: "running",
      driver: "claude",
      startedAt: ago(3 * 60 * 1000),
    },
  ],
};

const MOCK_INBOX_ITEMS = {
  items: [
    {
      name: "pr-summary-2026-04-24.md",
      path: "~/.patchwork/inbox/pr-summary-2026-04-24.md",
      modifiedAt: new Date(ago(41 * 60 * 1000)).toISOString(),
      preview: "Found 3 open PRs across patchwork-os. feat/demo-mode awaiting review, fix/bridge-status merged, chore/deps-bump draft.",
    },
    {
      name: "sprint-review-prep-2026-04-24.md",
      path: "~/.patchwork/inbox/sprint-review-prep-2026-04-24.md",
      modifiedAt: new Date(ago(118 * 60 * 1000)).toISOString(),
      preview: "Sprint review digest compiled. 12 issues closed this sprint. Summary posted to #engineering on Slack.",
    },
    {
      name: "morning-brief-2026-04-24.md",
      path: "~/.patchwork/inbox/morning-brief-2026-04-24.md",
      modifiedAt: new Date(ago(6 * 60 * 60 * 1000)).toISOString(),
      preview: "Good morning. 4 unread emails, 2 Linear P1s assigned, 1 Slack DM, 3 calendar events today.",
    },
  ],
};

const MOCK_INBOX_DETAIL: Record<string, { name: string; content: string; modifiedAt: string }> = {
  "pr-summary-2026-04-24.md": {
    name: "pr-summary-2026-04-24.md",
    modifiedAt: new Date(ago(41 * 60 * 1000)).toISOString(),
    content: `# PR Summary — April 24, 2026

> Generated by task [task-1](/dashboard/tasks) · ran 45 min ago

## Open Pull Requests

| # | Title | Status | Author |
|---|-------|--------|--------|
| 142 | feat/demo-mode dashboard | **Awaiting review** | kungfuk3nnyyy |
| 139 | fix/bridge-status unify | Merged | kungfuk3nnyyy |
| 138 | chore/deps-bump alpha.29 | Draft | kungfuk3nnyyy |

## Notes

- PR #142 has been open for 2 days — nudge in #engineering if no review by EOD.
- PR #139 shipped in alpha.29, closes issue #134.
- PR #138 is blocked on a failing test in \`webhookRecipes.test.ts\`.

---
_Posted to #engineering · Patchwork OS_
`,
  },
  "sprint-review-prep-2026-04-24.md": {
    name: "sprint-review-prep-2026-04-24.md",
    modifiedAt: new Date(ago(118 * 60 * 1000)).toISOString(),
    content: `# Sprint Review Prep — April 24, 2026

> Generated by task [task-2](/dashboard/tasks) · ran 2 hours ago

## Completed This Sprint (12 issues)

- **LIN-88** Fix bridge status inconsistency — shipped in alpha.29
- **LIN-87** Demo mode with seeded mock data — shipped in alpha.28
- **LIN-86** Connections redesign + SSE approvals — shipped in alpha.28
- **LIN-85** Actionable empty states and polling backoff — shipped in alpha.27
- **LIN-84** JetBrains plugin v1.0.0 — submitted to Marketplace
- *(7 more — see Linear sprint board)*

## In Progress

- **LIN-91** New recipe page UI overhaul *(~80% done)*
- **LIN-90** Inbox demo content *(in review)*

## Blockers

None currently.

---
_Sprint review is Friday at 2pm. Summary posted to #engineering._
`,
  },
  "morning-brief-2026-04-24.md": {
    name: "morning-brief-2026-04-24.md",
    modifiedAt: new Date(ago(6 * 60 * 60 * 1000)).toISOString(),
    content: `# Morning Brief — April 24, 2026

> Generated by recipe [morning-brief](/dashboard/recipes) · 6:00 AM

## 📧 Email (4 unread)

- **Vercel** — Your deployment patchwork-dashboard is live *(2h ago)*
- **GitHub** — [PR #142] Review requested: feat/demo-mode dashboard *(3h ago)*
- **Linear** — LIN-91 assigned to you: New recipe page UI *(5h ago)*
- **Stripe** — Invoice #1042 payment received *(yesterday)*

## 📋 Linear — Assigned to you (P1s)

- **LIN-91** New recipe page UI overhaul — *In Progress*
- **LIN-90** Inbox demo content — *In Review*

## 💬 Slack DMs (1 unread)

- **@alex** — "Hey, can you take a look at the staging env? seeing 502s on /api/bridge"

## 📅 Calendar (3 events today)

| Time | Event |
|------|-------|
| 10:00 AM | Standup — #engineering |
| 2:00 PM | Sprint review prep call |
| 4:30 PM | 1:1 with Alex |

---
_Patchwork OS morning-brief recipe · [manage recipe](/dashboard/recipes)_
`,
  },
};

// Chained run example: incident-war-room webhook → incident-notify → post-incident-report
const MOCK_RUNS = [
  {
    seq: 1,
    taskId: "task-run-1",
    recipeName: "incident-war-room",
    trigger: "webhook",
    status: "done",
    createdAt: ago(2 * 24 * 60 * 60 * 1000 + 2000),
    startedAt: ago(2 * 24 * 60 * 60 * 1000 + 1800),
    doneAt: ago(2 * 24 * 60 * 60 * 1000 - 14_000),
    durationMs: 15_800,
    model: "claude-opus-4-7",
    outputTail: "Incident summarised. Triggered incident-notify (seq 2).",
    childSeqs: [2],
  },
  {
    seq: 2,
    taskId: "task-run-2",
    recipeName: "incident-notify",
    trigger: "recipe",
    status: "done",
    createdAt: ago(2 * 24 * 60 * 60 * 1000 - 14_000),
    startedAt: ago(2 * 24 * 60 * 60 * 1000 - 14_200),
    doneAt: ago(2 * 24 * 60 * 60 * 1000 - 21_400),
    durationMs: 7_200,
    model: "claude-opus-4-7",
    outputTail: "Posted to #incidents. Paged @on-call. Triggered post-incident-report (seq 3).",
    parentSeq: 1,
    childSeqs: [3],
  },
  {
    seq: 3,
    taskId: "task-run-3",
    recipeName: "post-incident-report",
    trigger: "recipe",
    status: "done",
    createdAt: ago(2 * 24 * 60 * 60 * 1000 - 21_400),
    startedAt: ago(2 * 24 * 60 * 60 * 1000 - 21_600),
    doneAt: ago(2 * 24 * 60 * 60 * 1000 - 32_800),
    durationMs: 11_200,
    model: "claude-opus-4-7",
    outputTail: "Post-incident report appended to Notion page 'Incident Log — April 2026'.",
    parentSeq: 2,
  },
  {
    seq: 4,
    taskId: "task-run-4",
    recipeName: "morning-brief",
    trigger: "cron",
    status: "done",
    createdAt: ago(18 * 60 * 60 * 1000 + 1000),
    startedAt: ago(18 * 60 * 60 * 1000 + 800),
    doneAt: ago(18 * 60 * 60 * 1000 - 9_200),
    durationMs: 10_000,
    model: "claude-sonnet-4-6",
    outputTail: "Morning brief compiled and posted to #general.",
  },
];

const MOCK_ACTIVITY = {
  events: [
    { id: 1, kind: "tool", tool: "github.list_pull_requests", status: "success", durationMs: 312, at: ago(2 * 60 * 1000) },
    { id: 2, kind: "tool", tool: "slack.post_message", status: "success", durationMs: 88, at: ago(6 * 60 * 1000) },
    { id: 3, kind: "tool", tool: "linear.list_issues", status: "success", durationMs: 204, at: ago(12 * 60 * 1000) },
    { id: 4, kind: "tool", tool: "github.create_pull_request", status: "error", errorMessage: "Awaiting approval", durationMs: 0, at: ago(15 * 60 * 1000) },
    { id: 5, kind: "tool", tool: "linear.create_issue", status: "success", durationMs: 176, at: ago(28 * 60 * 1000) },
    { id: 6, kind: "lifecycle", event: "approval_decision", metadata: { decision: "approve", toolName: "slack.post_message" }, at: ago(35 * 60 * 1000) },
    { id: 7, kind: "tool", tool: "notion.append_block", status: "success", durationMs: 445, at: ago(52 * 60 * 1000) },
    { id: 8, kind: "tool", tool: "gmail.list_messages", status: "success", durationMs: 390, at: ago(70 * 60 * 1000) },
  ],
};

const MOCK_METRICS = `# HELP bridge_uptime_seconds Seconds since bridge start
# TYPE bridge_uptime_seconds gauge
bridge_uptime_seconds ${Math.round((Date.now() - SESSION_START) / 1000)}
# HELP bridge_tool_calls_total Total tool calls handled
# TYPE bridge_tool_calls_total counter
bridge_tool_calls_total{status="success"} 47
bridge_tool_calls_total{status="error"} 3
# HELP bridge_active_sessions Active MCP sessions
# TYPE bridge_active_sessions gauge
bridge_active_sessions 2
# HELP bridge_pending_approvals Pending approval requests
# TYPE bridge_pending_approvals gauge
bridge_pending_approvals 3
# HELP bridge_automation_hooks_total Automation hooks fired
# TYPE bridge_automation_hooks_total counter
bridge_automation_hooks_total{hook="onFileSave"} 8
bridge_automation_hooks_total{hook="onDiagnosticsStateChange"} 4
# HELP bridge_recipe_runs_total Recipe runs completed
# TYPE bridge_recipe_runs_total counter
bridge_recipe_runs_total{status="done"} 4
bridge_recipe_runs_total{status="error"} 0
# HELP bridge_ws_connections_total WebSocket connections since start
# TYPE bridge_ws_connections_total counter
bridge_ws_connections_total 7
`;

const MOCK_STATUS = {
  ok: true,
  port: 3100,
  workspace: "~/projects/patchwork-os",
  uptimeMs: Date.now() - SESSION_START,
  activeSessions: 1,
  extensionConnected: true,
  extension: true,
  slim: false,
  // Nested under `patchwork` so dashboard components see the same shape
  // they get from the real bridge `/status` response.
  patchwork: {
    workspace: "~/projects/patchwork-os",
    port: 3100,
    approvalGate: "high" as const,
    enableTimeOfDayAnomaly: true,
    fullMode: true,
    driver: "subprocess",
    model: "claude",
    automationEnabled: false,
    webhookUrl: null,
  },
};

const MOCK_HEALTH = {
  status: "ok",
  uptimeMs: Date.now() - SESSION_START,
  connections: 1,
  extensionConnected: true,
  extensionVersion: "2.46.0",
  activeSessions: 1,
  extensionCircuitBreaker: { suspended: false, suspendedUntil: 0, failures: 0, openCount: 0, lastOpenedAt: null },
  lastDisconnectReason: null,
};

const MOCK_CONNECTORS_STATUS = [
  { name: "github", status: "connected" },
  { name: "slack", status: "connected" },
  { name: "linear", status: "connected" },
  { name: "gmail", status: "disconnected" },
  { name: "notion", status: "disconnected" },
];

// /api/connections shape (ConnectorStatus[] with id field)
const MOCK_CONNECTIONS = {
  connectors: [
    { id: "github",  status: "connected",    lastSync: new Date(ago(2  * 60 * 1000)).toISOString() },
    { id: "slack",   status: "connected",    lastSync: new Date(ago(6  * 60 * 1000)).toISOString() },
    { id: "linear",  status: "connected",    lastSync: new Date(ago(12 * 60 * 1000)).toISOString() },
    { id: "gmail",   status: "disconnected" },
    { id: "notion",  status: "disconnected" },
  ],
};

const MOCK_TEMPLATES = {
  version: "1",
  updated_at: new Date().toISOString(),
  recipes: [
    {
      name: "@patchworkos/morning-brief",
      version: "1.0.0",
      description: "Daily 6am digest: Gmail unread, Linear assigned issues, Slack DMs, and today's calendar — composed into one Slack message.",
      tags: ["productivity", "morning", "daily"],
      connectors: ["gmail", "linear", "slack", "calendar"],
      install: "github:patchworkos/recipes/recipes/morning-brief",
      downloads: 0,
    },
    {
      name: "@patchworkos/incident-war-room",
      version: "1.0.0",
      description: "Ops incident response: summarize alert, open Linear issue, post to #incidents Slack, then append post-incident summary to Notion.",
      tags: ["ops", "incident", "on-call"],
      connectors: ["linear", "slack", "notion"],
      install: "github:patchworkos/recipes/recipes/incident-war-room",
      downloads: 0,
    },
    {
      name: "@patchworkos/sprint-review-prep",
      version: "1.0.0",
      description: "Pull completed Linear issues for the current sprint, summarize with AI, post digest to #engineering Slack channel.",
      tags: ["engineering", "sprint"],
      connectors: ["linear", "slack"],
      install: "github:patchworkos/recipes/recipes/sprint-review-prep",
      downloads: 0,
    },
    {
      name: "@patchworkos/customer-escalation",
      version: "1.0.0",
      description: "Zendesk ticket escalation pipeline: fetch ticket, create linked Linear issue, alert #support-escalations on Slack.",
      tags: ["support", "escalation"],
      connectors: ["zendesk", "linear", "slack"],
      install: "github:patchworkos/recipes/recipes/customer-escalation",
      downloads: 0,
    },
    {
      name: "@patchworkos/deal-won-celebration",
      version: "1.0.0",
      description: "HubSpot deal closed-won trigger: celebrate in #wins Slack, log deal details to a Notion database.",
      tags: ["sales", "hubspot", "crm"],
      connectors: ["hubspot", "slack", "notion"],
      install: "github:patchworkos/recipes/recipes/deal-won-celebration",
      downloads: 0,
    },
  ],
};

const MOCK_SESSIONS: Array<{
  id: string; connectedAt: string; openedFileCount: number; pendingApprovals: number;
  firstTool?: string; remoteAddr?: string; toolCount?: number;
  lastActivityAt?: number; clientType?: string;
}> = [
  {
    id: "sess-demo",
    connectedAt: new Date(ago(3 * 60 * 60 * 1000)).toISOString(),
    openedFileCount: 14,
    pendingApprovals: 3,
    firstTool: "getGitStatus",
    remoteAddr: "127.0.0.1",
    toolCount: 47,
    lastActivityAt: ago(2 * 60 * 1000),
    clientType: "claude-code",
  },
  {
    id: "sess-mobile",
    connectedAt: new Date(ago(30 * 60 * 1000)).toISOString(),
    openedFileCount: 0,
    pendingApprovals: 0,
    firstTool: "getBridgeStatus",
    remoteAddr: "192.168.1.42",
    toolCount: 6,
    lastActivityAt: ago(28 * 60 * 1000),
    clientType: "remote",
  },
];

const MOCK_ANALYTICS = {
  topTools: [
    { tool: "github.list_pull_requests",   calls: 18, errors: 0, p50Ms: 310,  p95Ms: 620  },
    { tool: "linear.list_issues",           calls: 15, errors: 1, p50Ms: 198,  p95Ms: 540  },
    { tool: "slack.post_message",           calls: 12, errors: 0, p50Ms: 88,   p95Ms: 210  },
    { tool: "gmail.list_messages",          calls: 9,  errors: 0, p50Ms: 394,  p95Ms: 890  },
    { tool: "github.create_pull_request",   calls: 7,  errors: 2, p50Ms: 850,  p95Ms: 2100 },
    { tool: "linear.create_issue",          calls: 6,  errors: 0, p50Ms: 174,  p95Ms: 380  },
    { tool: "notion.append_block",          calls: 5,  errors: 0, p50Ms: 441,  p95Ms: 910  },
    { tool: "slack.list_channels",          calls: 4,  errors: 0, p50Ms: 72,   p95Ms: 145  },
    { tool: "github.get_repository",        calls: 3,  errors: 0, p50Ms: 220,  p95Ms: 480  },
    { tool: "calendar.list_events",         calls: 3,  errors: 0, p50Ms: 315,  p95Ms: 670  },
  ],
  hooksLast24h: 12,
  recentAutomationTasks: [
    { id: "task-1", name: "Review open PRs and summarise for standup", status: "done",      startedAt: ago(45 * 60 * 1000),         completedAt: ago(41 * 60 * 1000) },
    { id: "task-2", name: "Run sprint-review-prep recipe",             status: "done",      startedAt: ago(2 * 60 * 60 * 1000),     completedAt: ago(118 * 60 * 1000) },
    { id: "task-3", name: "Check Linear backlog for P0 issues",        status: "running",   startedAt: ago(3 * 60 * 1000) },
  ],
};

const MOCK_TRACES = {
  traces: [
    {
      traceType: "approval",
      ts: ago(4 * 60 * 1000),
      key: "demo-1",
      summary: "Approved: github.create_pull_request — Open PR: feat/demo-mode dashboard",
      body: { decision: "approve", toolName: "github.create_pull_request", callId: "demo-1", sessionId: "sess-demo" },
    },
    {
      traceType: "approval",
      ts: ago(11 * 60 * 1000),
      key: "demo-2",
      summary: "Approved: slack.post_message — Post to #engineering: sprint review prep",
      body: { decision: "approve", toolName: "slack.post_message", callId: "demo-2", sessionId: "sess-demo" },
    },
    {
      traceType: "recipe_run",
      ts: ago(45 * 60 * 1000),
      key: "run-4",
      summary: "morning-brief completed in 10.0s (cron)",
      body: { recipeName: "morning-brief", trigger: "cron", status: "done", durationMs: 10000, seq: 4 },
    },
    {
      traceType: "recipe_run",
      ts: ago(2 * 24 * 60 * 60 * 1000),
      key: "run-1",
      summary: "incident-war-room completed in 15.8s (webhook) → chained 2 recipes",
      body: { recipeName: "incident-war-room", trigger: "webhook", status: "done", durationMs: 15800, seq: 1 },
    },
    {
      traceType: "decision",
      ts: ago(18 * 60 * 1000),
      key: "arch-001",
      summary: "Chose SSE over WebSocket polling for approvals stream",
      body: {
        ref: "#134",
        problem: "Polling /approvals every 2s caused unnecessary load and added latency to approval UI",
        solution: "Switch approvals feed to SSE — persistent connection, server-pushed events, lower overhead",
        workspace: "~/projects/patchwork-os",
        sessionId: "sess-demo",
        tags: ["architecture", "approvals", "sse"],
      },
    },
    {
      traceType: "decision",
      ts: ago(2 * 24 * 60 * 60 * 1000),
      key: "arch-002",
      summary: "Use trigger:recipe field to represent chained recipe invocations",
      body: {
        ref: "#141",
        problem: "No way to distinguish webhook-triggered vs recipe-triggered runs in the UI",
        solution: "Added trigger:'recipe' variant to Run type; chained runs set this field + reference parent seq",
        workspace: "~/projects/patchwork-os",
        sessionId: "sess-demo",
        tags: ["architecture", "recipes", "runs"],
      },
    },
    {
      traceType: "enrichment",
      ts: ago(35 * 60 * 1000),
      key: "commit-e001d25",
      summary: "Commit e001d25 linked to LIN-88, LIN-89",
      body: { commitHash: "e001d25", issueRefs: ["LIN-88", "LIN-89"], branch: "main", message: "chore: bump to 0.2.0-alpha.29" },
    },
  ],
  count: 7,
  sources: { approval: true, enrichment: true, recipe_run: true, decision: true },
};

const MOCK_DECISIONS = {
  traces: [
    {
      traceType: "decision",
      ts: ago(18 * 60 * 1000),
      key: "arch-001",
      summary: "Chose SSE over WebSocket polling for approvals stream",
      body: {
        ref: "#134",
        problem: "Polling /approvals every 2s caused unnecessary load and added latency to approval UI",
        solution: "Switch approvals feed to SSE — persistent connection, server-pushed events, lower overhead",
        workspace: "~/projects/patchwork-os",
        sessionId: "sess-demo",
        tags: ["architecture", "approvals", "sse"],
      },
    },
    {
      traceType: "decision",
      ts: ago(2 * 24 * 60 * 60 * 1000),
      key: "arch-002",
      summary: "Use trigger:recipe field to represent chained recipe invocations",
      body: {
        ref: "#141",
        problem: "No way to distinguish webhook-triggered vs recipe-triggered runs in the UI",
        solution: "Added trigger:'recipe' variant to Run type; chained runs set this field + reference parent seq",
        workspace: "~/projects/patchwork-os",
        sessionId: "sess-demo",
        tags: ["architecture", "recipes", "runs"],
      },
    },
    {
      traceType: "decision",
      ts: ago(5 * 24 * 60 * 60 * 1000),
      key: "arch-003",
      summary: "Mock data uses id field instead of taskId — fixed field name",
      body: {
        ref: "#138",
        problem: "Tasks page crashed with 'Cannot read properties of undefined (reading slice)' in demo mode",
        solution: "Renamed id → taskId in MOCK_TASKS to match the Task interface expected by page.tsx",
        workspace: "~/projects/patchwork-os",
        sessionId: "sess-demo",
        tags: ["bug", "demo", "tasks"],
      },
    },
  ],
  count: 3,
  sources: { decision: true },
};

const MOCK_STEP_RESULTS: Record<number, Array<{ stepId: string; tool?: string; status: string; durationMs: number; output?: string; error?: string }>> = {
  1: [
    { stepId: "fetch-alert",    tool: "webhook.get_payload",          status: "ok",    durationMs: 12,   output: '{"alert":"High CPU on prod-api-3","severity":"critical"}' },
    { stepId: "summarise",      tool: "claude.complete",              status: "ok",    durationMs: 3200, output: "Prod-api-3 CPU spiked to 98% at 14:32 UTC. Likely cause: runaway query in analytics aggregation job." },
    { stepId: "create-issue",   tool: "linear.create_issue",          status: "ok",    durationMs: 174,  output: '{"id":"LIN-92","url":"https://linear.app/patchwork/issue/LIN-92"}' },
    { stepId: "post-slack",     tool: "slack.post_message",           status: "ok",    durationMs: 88,   output: '{"ts":"1745500352.000100","channel":"C08PQ"}' },
    { stepId: "chain-notify",   tool: "recipe.run",                   status: "ok",    durationMs: 320,  output: "Triggered incident-notify (seq 2)" },
  ],
  2: [
    { stepId: "post-incidents", tool: "slack.post_message",           status: "ok",    durationMs: 91,   output: '{"ts":"1745500366.000200","channel":"C08INC"}' },
    { stepId: "page-oncall",    tool: "pagerduty.create_incident",    status: "ok",    durationMs: 210,  output: '{"incident_key":"i-8823","status":"triggered"}' },
    { stepId: "chain-report",   tool: "recipe.run",                   status: "ok",    durationMs: 280,  output: "Triggered post-incident-report (seq 3)" },
  ],
  3: [
    { stepId: "fetch-timeline", tool: "linear.get_issue",             status: "ok",    durationMs: 198,  output: '{"id":"LIN-92","state":"in_progress"}' },
    { stepId: "write-report",   tool: "claude.complete",              status: "ok",    durationMs: 4100, output: "Post-incident report drafted: root cause, timeline, remediation steps." },
    { stepId: "append-notion",  tool: "notion.append_block",          status: "ok",    durationMs: 441,  output: '{"object":"block","id":"abc123"}' },
  ],
  4: [
    { stepId: "fetch-email",    tool: "gmail.list_messages",          status: "ok",    durationMs: 394,  output: '{"messages":4,"unread":4}' },
    { stepId: "fetch-linear",   tool: "linear.list_issues",           status: "ok",    durationMs: 198,  output: '{"issues":2}' },
    { stepId: "fetch-calendar", tool: "calendar.list_events",         status: "ok",    durationMs: 315,  output: '{"events":3}' },
    { stepId: "compose",        tool: "claude.complete",              status: "ok",    durationMs: 2800, output: "Morning brief composed (4 emails, 2 issues, 3 events)." },
    { stepId: "post-slack",     tool: "slack.post_message",           status: "ok",    durationMs: 88,   output: '{"ts":"1745464800.000100","channel":"C08GEN"}' },
  ],
};

const MOCK_APPROVAL_INSIGHTS = {
  generatedAt: new Date().toISOString(),
  totalDecisions: 47,
  trustedToolCount: 4,
  rejectedToolCount: 1,
  tools: [
    {
      toolName: "github.list_pull_requests",
      approvals: 18,
      rejections: 0,
      approvalRate: 1,
      lastDecisionAt: new Date(ago(2 * 60 * 1000)).toISOString(),
      firstDecisionAt: new Date(ago(7 * 24 * 60 * 60 * 1000)).toISOString(),
      heuristicLabel: "Approved 18× consecutively — looks trusted.",
      severity: "low" as const,
    },
    {
      toolName: "slack.post_message",
      approvals: 12,
      rejections: 0,
      approvalRate: 1,
      lastDecisionAt: new Date(ago(6 * 60 * 1000)).toISOString(),
      firstDecisionAt: new Date(ago(5 * 24 * 60 * 60 * 1000)).toISOString(),
      heuristicLabel: "Frequent low-risk write — consider auto-approve.",
      severity: "low" as const,
    },
    {
      toolName: "linear.list_issues",
      approvals: 14,
      rejections: 1,
      approvalRate: 14 / 15,
      lastDecisionAt: new Date(ago(12 * 60 * 1000)).toISOString(),
      firstDecisionAt: new Date(ago(6 * 24 * 60 * 60 * 1000)).toISOString(),
      heuristicLabel: "Mostly approved with one rejection.",
      severity: "medium" as const,
    },
    {
      toolName: "github.create_pull_request",
      approvals: 5,
      rejections: 2,
      approvalRate: 5 / 7,
      lastDecisionAt: new Date(ago(15 * 60 * 1000)).toISOString(),
      firstDecisionAt: new Date(ago(3 * 24 * 60 * 60 * 1000)).toISOString(),
      heuristicLabel: "External write — review each invocation.",
      severity: "medium" as const,
    },
    {
      toolName: "linear.create_issue",
      approvals: 3,
      rejections: 0,
      approvalRate: 1,
      lastDecisionAt: new Date(ago(28 * 60 * 1000)).toISOString(),
      firstDecisionAt: new Date(ago(2 * 24 * 60 * 60 * 1000)).toISOString(),
      heuristicLabel: "New tool — building history.",
      severity: "medium" as const,
    },
    {
      toolName: "shell.rm_rf",
      approvals: 0,
      rejections: 3,
      approvalRate: 0,
      lastDecisionAt: new Date(ago(2 * 24 * 60 * 60 * 1000)).toISOString(),
      firstDecisionAt: new Date(ago(2 * 24 * 60 * 60 * 1000)).toISOString(),
      heuristicLabel: "Always rejected — consider deny rule.",
      severity: "high" as const,
    },
  ],
};

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

export function mockBridgeResponse(pathname: string, method = "GET"): Response | null {
  // strip query string for matching
  const path = pathname.split("?")[0];

  if (path === "/inbox" && method === "GET") return json(MOCK_INBOX_ITEMS);
  if (path.startsWith("/inbox/") && method === "GET") {
    const filename = decodeURIComponent(path.slice("/inbox/".length));
    const detail = MOCK_INBOX_DETAIL[filename];
    if (detail) return json(detail);
    return json({ error: "not found" }, 404);
  }
  if (path === "/status")                  return json(MOCK_STATUS);
  if (path === "/health")                  return json(MOCK_HEALTH);
  if (path === "/approvals" && method === "GET") return json(MOCK_APPROVALS);
  // Demo mode: short-circuit approve/reject so destructive clicks don't fall
  // through to a real bridge that may happen to be running locally.
  if ((path.startsWith("/approve/") || path.startsWith("/reject/")) && method === "POST") {
    return json({ ok: true, demo: true });
  }
  if (path.startsWith("/suggestions") && method === "GET") {
    return json({
      generatedAt: new Date().toISOString(),
      suggestions: [
        {
          kind: "co_occurring_pair",
          label:
            "You called git.log_since and git.stale_branches together 17 times in the last 7 days. Create a recipe?",
          details: { pair: ["git.log_since", "git.stale_branches"], count: 17 },
        },
        {
          kind: "co_occurring_pair",
          label:
            "You called gmail.fetch_unread and slack.post_message together 6 times in the last 7 days. Create a recipe?",
          details: { pair: ["gmail.fetch_unread", "slack.post_message"], count: 6 },
        },
        {
          kind: "recipe_trust_graduation",
          label:
            "branch-health has succeeded 23 times in a row — consider auto-approving.",
          details: { recipeName: "branch-health", runs: 23 },
        },
        {
          kind: "installed_but_unused",
          label:
            "12 installed tools haven't been called in 7 days: jira.search_issues, asana.list_projects, gitlab.list_mrs, datadog.list_monitors, pagerduty.list_incidents, … (+7 more)",
          details: {
            unusedCount: 12,
            examples: [
              "jira.search_issues",
              "asana.list_projects",
              "gitlab.list_mrs",
              "datadog.list_monitors",
              "pagerduty.list_incidents",
            ],
          },
        },
      ],
    });
  }
  if (path === "/transactions" && method === "GET") {
    return json({
      transactions: [
        {
          id: "tx-7c9f3a",
          createdAt: ago(8 * 60 * 1000),
          expiresAt: ago(-22 * 60 * 1000),
          edits: [
            {
              filePath: "/Users/dev/proj/src/auth/refresh.ts",
              sizeBefore: 4287,
              sizeAfter: 4612,
              lineDelta: 14,
            },
            {
              filePath: "/Users/dev/proj/src/auth/__tests__/refresh.test.ts",
              sizeBefore: 1820,
              sizeAfter: 2156,
              lineDelta: 18,
            },
            {
              filePath: "/Users/dev/proj/src/auth/types.ts",
              sizeBefore: 612,
              sizeAfter: 595,
              lineDelta: -2,
            },
          ],
        },
        {
          id: "tx-2b41d8",
          createdAt: ago(45 * 60 * 1000),
          expiresAt: ago(-15 * 60 * 1000),
          edits: [
            {
              filePath: "/Users/dev/proj/src/legacy/migrate.ts",
              sizeBefore: 9821,
              sizeAfter: 9405,
              lineDelta: -22,
            },
          ],
        },
      ],
    });
  }
  if (path.match(/^\/transactions\/[^/]+\/rollback$/) && method === "POST") {
    return json({ ok: true, demo: true });
  }
  if (path.startsWith("/webhook-payloads/") && method === "GET") {
    const hookPath = path.substring("/webhook-payloads".length);
    if (hookPath === "/incident-war-room") {
      return json({
        path: hookPath,
        entries: [
          {
            receivedAt: ago(7 * 60 * 1000),
            payload: {
              alert_id: "PD-93812",
              service: "checkout-api",
              severity: "critical",
              summary: "p99 latency over 2s for 5min",
            },
            ok: true,
            taskId: "task-incident-7",
            recipeName: "incident-war-room",
          },
          {
            receivedAt: ago(2 * 60 * 60 * 1000),
            payload: { test: true, sentAt: new Date(ago(2 * 60 * 60 * 1000)).toISOString() },
            ok: true,
            taskId: "task-incident-6",
            recipeName: "incident-war-room",
          },
          {
            receivedAt: ago(8 * 60 * 60 * 1000),
            payload: "raw text body — non-JSON sender",
            ok: false,
            error: "step 2 failed: linear.create_issue rate-limited",
            recipeName: "incident-war-room",
          },
        ],
      });
    }
    return json({ path: hookPath, entries: [] });
  }
  // Detail fixture: synthesize a pending response from MOCK_APPROVALS so the
  // detail page renders cards (matched-rule, risk signals, params, nearby) in
  // demo mode. Without this, every detail URL hits the empty fallthrough and
  // shows "Unknown callId" — confusing for someone exploring the demo.
  {
    const m = path.match(/^\/approvals\/([^/]+)$/);
    if (m && method === "GET") {
      const id = decodeURIComponent(m[1]);
      const a = MOCK_APPROVALS.find((x) => x.callId === id);
      if (a) {
        return json({
          pending: {
            ...a,
            params:
              id === "demo-1"
                ? { repo: "Oolab-labs/patchwork-os", title: "feat/demo-mode dashboard" }
                : id === "demo-2"
                  ? { channel: "#engineering", text: "Sprint review prep at 3pm" }
                  : { team: "Engineering", title: "Fix bridge status inconsistency", priority: "High" },
            riskSignals:
              id === "demo-3"
                ? [
                    { kind: "external_write", label: "external write", severity: "high" as const },
                    { kind: "first_use", label: "first time used today", severity: "medium" as const },
                  ]
                : [],
          },
          decision: null,
          nearby: [],
        });
      }
      return json({ pending: null, decision: null, nearby: [] }, 404);
    }
  }
  if (path === "/approval-insights" && method === "GET") return json(MOCK_APPROVAL_INSIGHTS);
  if (path === "/approval-insights/explain" && method === "GET") {
    return json({ tool: pathname.split("tool=")[1] ?? "", specifier: null, explanation: null });
  }
  if (path === "/cc-permissions" && method === "GET") {
    return json({ allow: ["Bash(npm test)"], ask: ["Bash(npm publish)"], deny: [], workspace: "~/projects/patchwork-os", attributed: { allow: [], ask: [], deny: [] } });
  }
  if (path === "/recipes" && method === "GET")   return json({ recipes: MOCK_RECIPES });
  if (path === "/tasks" && method === "GET")     return json(MOCK_TASKS);
  if (path === "/activity")               return json(MOCK_ACTIVITY);
  if (path === "/metrics")                return new Response(MOCK_METRICS, { status: 200, headers: { "content-type": "text/plain" } });
  if (path === "/templates")              return json(MOCK_TEMPLATES);
  if (path === "/connectors/status")      return json(MOCK_CONNECTORS_STATUS);
  if (path === "/connections" && method === "GET") return json(MOCK_CONNECTIONS);
  if (path === "/runs")                   return json({ runs: MOCK_RUNS });
  if (/^\/runs\/\d+\/plan$/.test(path))   return json({ error: "no plan in demo" }, 404);
  if (/^\/runs\/(\d+)$/.test(path)) {
    const seq = parseInt(path.split("/")[2], 10);
    const run = MOCK_RUNS.find((r) => r.seq === seq);
    if (!run) return json({ error: "not found" }, 404);
    return json({ run: { ...run, stepResults: MOCK_STEP_RESULTS[seq] ?? [] } });
  }
  if (path === "/sessions")               return json(MOCK_SESSIONS);
  if (path.startsWith("/analytics"))      return json(MOCK_ANALYTICS);
  if (path.startsWith("/traces") && pathname.includes("traceType=decision")) return json(MOCK_DECISIONS);
  if (path.startsWith("/traces"))         return json(MOCK_TRACES);

  // write operations in demo mode — acknowledge but don't mutate
  if (method === "POST" || method === "PATCH" || method === "PUT" || method === "DELETE") {
    return json({ ok: true, demo: true });
  }

  // unknown GET — return empty so UI degrades gracefully
  return json({});
}
