import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execSafe, optionalString, requireString, success } from "./utils.js";

export function createOpenInBrowserTool() {
  return {
    schema: {
      name: "openInBrowser",
      description:
        "Write a self-contained HTML document to a temp file and open it in the system default browser. Returns the file path. Use this to display visual reports, dashboards, or graphs generated by skills.",
      extensionRequired: false,
      annotations: {
        title: "Open HTML in Browser",
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
      inputSchema: {
        $schema: "http://json-schema.org/draft-07/schema#",
        type: "object",
        additionalProperties: false,
        required: ["html"],
        properties: {
          html: {
            type: "string",
            description: "Full self-contained HTML document content",
          },
          filename: {
            type: "string",
            description:
              "Optional filename (basename only, must end in .html). Defaults to report-<timestamp>.html",
          },
        },
      },
    },

    async handler(args: Record<string, unknown>) {
      const html = requireString(args, "html", 10 * 1024 * 1024);
      const rawFilename = optionalString(args, "filename", 256);

      // Sanitize filename: strip to basename, reject traversal, require .html extension
      let sanitizedFilename: string;
      if (rawFilename) {
        const base = path.basename(rawFilename);
        if (
          base !== rawFilename ||
          base.includes("..") ||
          !base.endsWith(".html")
        ) {
          sanitizedFilename = `report-${Date.now()}.html`;
        } else {
          sanitizedFilename = base;
        }
      } else {
        sanitizedFilename = `report-${Date.now()}.html`;
      }

      const tmpPath = path.join(os.tmpdir(), sanitizedFilename);
      await fs.writeFile(tmpPath, html, "utf8");

      const platform = process.platform;
      if (platform === "darwin") {
        await execSafe("open", [tmpPath]);
      } else if (platform === "win32") {
        await execSafe("cmd", ["/c", "start", "", tmpPath]);
      } else {
        await execSafe("xdg-open", [tmpPath]);
      }

      return success({ path: tmpPath });
    },
  };
}
